services:
  codex:
    image: enarciso/codex-runner:latest
    pull_policy: always
    restart: no
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}:/workspace
      - ${HOME}/.codex:/home/ubuntu/.codex
    working_dir: /workspace
    tty: true
    stdin_open: true
    privileged: true
    entrypoint:
      - "/usr/bin/bash"
      - "-l"
      - "-c"
    command:
      - "bash"
